apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: boot-admin-discoverer
rules:
  - verbs: ["get", "list", "watch"]
    apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
