apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: boot-admin-role-binding
subjects:
  - kind: ServiceAccount
    name: spring-boot-admin-service-account
roleRef:
  apiGroup: ""
  kind: Role
  name: boot-admin-discoverer