apiVersion: v1
kind: Service
metadata:
  name: spring-boot-admin-service
  labels:
    techstack: spring-boot
spec:
  selector:
    app: spring-boot-admin
  ports:
    - port: 8081
      name: http
  type: LoadBalancer